apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: local-pv
  resources:
    requests:
      storage: 1Mi