apiVersion: v1
kind: Pod
metadata:
  name: vol-pod1
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: local-volume
          mountPath: /usr/local/bfm/dirOne
        - name: local-volume-two
          mountPath: /usr/local/bfm/dirTwo
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: nfs-pvc-dir-one
        readOnly: true
    - name: local-volume-two
      persistentVolumeClaim:
        claimName: nfs-pvc-dir-two
        readOnly: true