apiVersion: v1
kind: Pod
metadata:
  name: vol-pod2
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: local-volume
          mountPath: /usr/local/bfm/
  volumes:
    - name: local-volume
      persistentVolumeClaim:
        claimName: nfs-pvc
        readOnly: true