apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: cgroup-fun
  name: cgroup-fun
spec:
  containers:
  - image: busybox
    name: container-one
    command:
      - "sleep"
    args:
      - "infinity"
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 10Mi
  - image: busybox
    name: container-two
    command:
      - "sleep"
    args:
      - "infinity"
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 5m
        memory: 5Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
