apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cgroup-mem
  name: centos
spec:
  containers:
    - image: centos:test
      name: centos
      command:
        - tail
      args:
        - -f
        - '/tmp/hello-world.txt'
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
