apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cgroup-mem
  name: ubuntu
spec:
  containers:
    - image: ubuntu:test
      name: ubuntu
      command:
        - tail
      args:
        - -f
        - 'hello-world.txt'
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 10Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
